# Generated by Django 5.2.4 on 2025-08-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_user', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('bio', models.TextField(blank=True, default='')),
                ('profileimg', models.ImageField(default='blank-profile-picture', upload_to='profile_images')),
                ('location', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
