# Generated by Django 5.2.4 on 2025-08-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_followers_likepost_post_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='number_of_likes',
            new_name='no_of_likes',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
