# Generated by Django 5.2.4 on 2025-08-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_rename_number_of_likes_post_no_of_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='profile_images/blank-profile-picture.png', upload_to='profile_images'),
        ),
    ]
